### ISSUE TITLE
Setup essential middlewares cors, body-parser & morgan

### ISSUE THREAD

**Issue by irshadjsr21** [blitz450/nodejs#1]
## Description

**Cors**
Cors middleware adds additional headers to the response so that the content can be accessed by other domains. Refer this for additional guide https://expressjs.com/en/resources/middleware/cors.html

**Body parser**
Parse incoming request bodies in a middleware before your handlers, available under the req.body property.
https://www.npmjs.com/package/body-parser

**Morgan**
It is used to log the details of the incoming request and its response.
https://www.npmjs.com/package/morgan

Integrate all the above 3 middlewares in the express application.

**Comment by pundreek-saurabh** [comment]
I'll do it !

**Comment by pundreek-saurabh** [comment]
What is the deadline to complete all the above three tasks , i.e. Cors , body parser and Morgan ?

**Comment by irshadjsr21** [comment]
The deadline is this time tomorrow.

**Comment by pundreek-saurabh** [comment]
okay !

**Comment by kumarishivanisingh14** [comment]
I'll take upon this issue! Please assign me.

**Comment by blitz450** [comment]
Handled in PR #20 by @kumarishivanisingh14. Closing.
