### ISSUE TITLE
Modify Home page EJS view

### ISSUE THREAD

**Issue by irshadjsr21** [blitz450/nodejs#13]
## Description
Modify the `views/index.ejs` file to contain proper HTML structure and dummy home page contents. The home page must include:
- Navigation links to `/about`, `/contact`, `/signup`, `/login` at the top.
- `h1` Heading & page title as `Study Resources`.
- Description of the app (3-4 lines) below the heading. (description can be dummy text).

Styling the page is optional.

**Comment by ritika-0111** [comment]
@irshadjsr21 @blitz450 please assign this issue to me

**Comment by irshadjsr21** [comment]
You are already assigned to issue #8, you can take this up after that issue is resolved.

**Comment by ritika-0111** [comment]
I have completed issue #8 , and have made changes as per the instructions given by you
