### ISSUE TITLE
Create a 404 error page and setup it's route.

### ISSUE THREAD

**Issue by irshadjsr21** [blitz450/nodejs#15]
## Description
Create a `views/404.ejs` file with proper HTML structure and set up the express route such that the `404.ejs` view is rendered when no route is found. 

The 404 error page must include:
- `h1` Heading & page title as `Page not found`.
- The heading should be in the center of the page.
- A button below the heading to go back to the home page (`/` route).

Styling the page is optional.
Refer [this](https://www.hacksparrow.com/webdev/express/custom-error-pages-404-and-500.html) for setting up 404 route in express.

**Comment by ritika-0111** [comment]
Please assign this issue to me

**Comment by blitz450** [comment]
Handled in PR #21. Closing
