### ISSUE TITLE
Create an about page and setup it's route.

### ISSUE THREAD

**Issue by irshadjsr21** [blitz450/nodejs#16]
## Description
Create a `views/about.ejs` file to contain proper HTML structure and dummy about page contents. The about page should be rendered on `/about` route. 

The about page must include:
- Navigation links to `/`, `/contact`, `/signup`, `/login` at the top.
- `h1` Heading & page title as `About`.
- Dummy about us text (3-4 lines) below the heading. 

Styling the page is optional.
Refer [this](https://learn.co/lessons/using-ejs-in-express) for using EJS templates in express.

**Comment by ritika-0111** [comment]
please assign this issue to me

**Comment by blitz450** [comment]
> please assign this issue to me

Sure 👍

**Comment by ritika-0111** [comment]
Do i need to use partial ejs templating and include navbar in about.ejs ?

**Comment by blitz450** [comment]
Handled in PR #22. Closing
