### ISSUE TITLE
Create a contact us page and setup it's route

### ISSUE THREAD

**Issue by irshadjsr21** [blitz450/nodejs#17]
## Description
Create a `views/contact.ejs` file to contain proper HTML structure and dummy contact page contents. The contact page should be rendered on `/contact` route. 

The about page must include:
- Navigation links to `/`, `/about`, `/signup`, `/login` at the top.
- `h1` Heading & page title as `Contact us`.
- Dummy contact us text (3-4 lines) below the heading. 

Styling the page is optional.
Refer [this](https://learn.co/lessons/using-ejs-in-express) for using EJS templates in express.

**Comment by pundreek-saurabh** [comment]
I'll solve this issue .

**Comment by irshadjsr21** [comment]
Sure, go ahead.

**Comment by ritika-0111** [comment]
please assign this issue to me

**Comment by blitz450** [comment]
Handled in #24 . Closing
