### ISSUE TITLE
Setup EJS templating engine with a demo template in `/` route.

### ISSUE THREAD

**Issue by irshadjsr21** [blitz450/nodejs#2]
## Description
Instead of using regular HTML, we will be using EJS templating engine which will give us extra features to write our HTML pages like loops, conditional statements, etc.

Setup EJS templating engine and a demo template in the `views` folder called `index.ejs`. This demo template can just contain an `h1` tag with Hello world text.

Setup the `/` route to render this demo template (`index.ejs`).

https://robdodson.me/how-to-use-ejs-in-express/

**Comment by KomalMadhu** [comment]
Hi,
I will be working on this issue. @irshadjsr21  can you please assign this issue to me?
Thanks.

**Comment by ritika-0111** [comment]
@irshadjsr21 please assign this issue to me
