### ISSUE TITLE
Create a header and footer template to be used in all pages.

### ISSUE THREAD

**Issue by blitz450** [blitz450/nodejs#23]
1. Create a header.ejs and footer.ejs template to be included in all views being served (home,about,contact,404,upload,signup,login).

2. Replace the header of already made pages(home,about,contact.,404 ..)

Header should have all the hyperlinks to the aforementioned pages.
Footer can be any dummy template. Feel free to be creative. 

Reference/Help: https://medium.com/@henslejoseph/ejs-partials-f6f102cb7433

**Comment by ritika-0111** [comment]
please assign this issue to me

**Comment by kumarishivanisingh14** [comment]
please assign this issue to me!

**Comment by blitz450** [comment]
Handled in PR #25. Closing
