### ISSUE TITLE
Create an error page and setup it's route.

### ISSUE THREAD

**Issue by irshadjsr21** [blitz450/nodejs#26]
## Description
Create a `views/error.ejs` file with proper HTML structure and set up the express route such that the `error.ejs` view is rendered when any error occurs on the server. 

The error page must include:
- `h1` Heading & page title as `Server error`.
- The heading should be in the center of the page.
- A button below the heading to go back to the home page (`/` route).

Styling the page is optional.
Refer [this](https://www.hacksparrow.com/webdev/express/custom-error-pages-404-and-500.html) for setting up error route in express.

**Comment by ritika-0111** [comment]
please assign this issue to me

**Comment by blitz450** [comment]
Handled in PR #30 . Closing
