### ISSUE TITLE
Create a resource upload page and setup it's route

### ISSUE THREAD

**Issue by irshadjsr21** [blitz450/nodejs#27]
## Description
Create a `views/upload.ejs` file to contain proper HTML structure. The upload page should be rendered on `/upload` route. 

The upload page must include:
- The default header and footer.
- A form containing `name` field & a submit button with action to `POST /upload`.

Styling the page is optional.
Refer [this](https://learn.co/lessons/using-ejs-in-express) for using EJS templates in express.

**Comment by ritika-0111** [comment]
please assign this issue to me

**Comment by ritika-0111** [comment]
please assign this issue to me

**Comment by blitz450** [comment]
Handled in PR #31
