### ISSUE TITLE
Create a resource model in mongoose

### ISSUE THREAD

**Issue by irshadjsr21** [blitz450/nodejs#28]
## Description
Create a resource model in `models/resource.js` file.
The model should have the following fields:
- `name` as String
- set `timestamps` to true (Refer [this](https://mongoosejs.com/docs/guide.html#timestamps))

You can refer [this](https://betech.info/how-to-create-mongoose-schema-and-data-model-in-node-js/) for more info

**Comment by ritika-0111** [comment]
please assign this issue to me

**Comment by blitz450** [comment]
Handled in PR #32
