### ISSUE TITLE
Setup a static folder named ‘public’ with demo image

### ISSUE THREAD

**Issue by irshadjsr21** [blitz450/nodejs#3]
## Description

Create & set up a static folder named `public` so that all its contents are automatically served by express.
Add a demo image in the `public` folder to see it working.

http://expressjs.com/en/starter/static-files.html

**Comment by blitz450** [comment]
This issue has been taken up by Kumari Shivani Singh in PR #4.  Closing.

**Comment by ritika-0111** [comment]
there is issue in set up of public folder

**Comment by ritika-0111** [comment]
claim

**Comment by ritika-0111** [comment]
done
