### ISSUE TITLE
Connect with Mongodb/Mongoose

### ISSUE THREAD

**Issue by blitz450** [blitz450/nodejs#7]
**MongoDB and Mongoose**
- Install MongoDB and Mongoose npm packages.  

- Require mongoose in app.js and connect with local database
https://mongoosejs.com/docs/connections.html

- Test your work by connecting to local mongo database on your machine.

**Comment by kumarishivanisingh14** [comment]
I am voluntarily willing to solve this issue. Please assign this issue to me.

**Comment by blitz450** [comment]
This issue has been handled in PR #11 . Closing.
