### ISSUE TITLE
Setup Multer

### ISSUE THREAD

**Issue by blitz450** [blitz450/nodejs#8]
**Multer:**
Multer is middleware for Express and Node.js that makes it easy to handle file uploads.

- Install Multer npm package.

- Require multer in app.js

- Write multer config (where to store files etc.)

_**Note**: You don't have to write client side code(i.e the html form to upload file) as that will be upcoming task. Just setup multer and write config code. Feel free to clear doubts beforehand._

[Reference/Help](https://code.tutsplus.com/tutorials/file-upload-with-multer-in-node--cms-32088)

**Comment by MohdAbdulRahman7** [comment]
I will take this up!

**Comment by irshadjsr21** [comment]
Sure go ahead. But before starting please provide your gitihub id, name and email on slack.

**Comment by ritika-0111** [comment]
@blitz450 @irshadjsr21 please assign this issue to me
